name: proto_run
description: "Capstone Prototype"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^3.11.0  # Core Firebase package (required)
  firebase_auth: ^5.4.2  # Firebase Authentication
  cloud_firestore: ^5.6.3  # Firestore Database
  firebase_database: ^11.3.2  # Realtime Database (optional)
  firebase_storage: ^12.4.2  # Firebase Storage (optional)
  cupertino_icons: ^1.0.8
  uuid: ^4.2.1
  js: ^0.7.1
  qr_flutter: ^4.1.0
  path_provider: ^2.1.2 # Get file paths
  permission_handler: ^11.0.1 # Handle storage permissions
  image: ^4.1.3 # Image processing
  gallery_saver: '^2.0.3'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
