name: proto_run
description: "Capstone Prototype"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^2.24.2  # Core Firebase package (required)
  firebase_auth: ^4.15.3  # Firebase Authentication
  cloud_firestore: ^4.14.0  # Firestore Database
  firebase_database: ^10.4.0  # Realtime Database (optional)
  firebase_storage: ^11.6.0  # Firebase Storage (optional)
  cupertino_icons: ^1.0.8
  uuid: ^4.2.1
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
