// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlv4wDBk0jsRcTSvMCq022nEcoKaXxPYA',
    appId: '1:396418626880:web:83f0c89570271784f1b6a5',
    messagingSenderId: '396418626880',
    projectId: 'wahhh-51ba9',
    authDomain: 'wahhh-51ba9.firebaseapp.com',
    storageBucket: 'wahhh-51ba9.firebasestorage.app',
    measurementId: 'G-TLCD9C9DZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmfMhcaqomX6lRmt2kq16Mo7mcftPg5U8',
    appId: '1:396418626880:android:660db345086545c3f1b6a5',
    messagingSenderId: '396418626880',
    projectId: 'wahhh-51ba9',
    storageBucket: 'wahhh-51ba9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX6ksvFyQwnBBKDtslCvSVMlnHSLZ348w',
    appId: '1:396418626880:ios:c85d78667eaec39af1b6a5',
    messagingSenderId: '396418626880',
    projectId: 'wahhh-51ba9',
    storageBucket: 'wahhh-51ba9.firebasestorage.app',
    iosBundleId: 'com.wahhh.protoRun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX6ksvFyQwnBBKDtslCvSVMlnHSLZ348w',
    appId: '1:396418626880:ios:c85d78667eaec39af1b6a5',
    messagingSenderId: '396418626880',
    projectId: 'wahhh-51ba9',
    storageBucket: 'wahhh-51ba9.firebasestorage.app',
    iosBundleId: 'com.wahhh.protoRun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlv4wDBk0jsRcTSvMCq022nEcoKaXxPYA',
    appId: '1:396418626880:web:44fe2def4d2b1aacf1b6a5',
    messagingSenderId: '396418626880',
    projectId: 'wahhh-51ba9',
    authDomain: 'wahhh-51ba9.firebaseapp.com',
    storageBucket: 'wahhh-51ba9.firebasestorage.app',
    measurementId: 'G-ZCEXBKG010',
  );
}
